version: '3.8'

services:
  xdmod:
    build: .
    container_name: xdmod-container
    hostname: xdmod.tcluster01.msu270
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      # Данные MySQL
      - mysql_data:/var/lib/mysql
      # SLURM данные с хоста
      - /var/log/slurm:/var/log/slurm:ro
      - /var/spool/slurm:/var/spool/slurm:ro
      - /opt/slurm:/opt/slurm:ro
      # Директория для экспорта данных
      - /opt/xdmod-data:/opt/xdmod-data
    environment:
      - MYSQL_ROOT_PASSWORD=secure_root_password_123
      - XDMOD_DB_PASSWORD=secure_xdmod_password_123
      - TZ=Europe/Moscow
    restart: unless-stopped

volumes:
  mysql_data: